version: '3'
services:
  db:
    image: postgres:11
    expose:
      - '5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: ${DOCKER_IMAGE_NAME-app}
    build: .
    env_file:
      - '.env.dev'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3006 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      # use cached bundle and node modules volume
      - bundle:/bundle
      #  put all the generated files into Docker volumes to avoid heavy disk operations on the host machine
      - node_modules:/app/node_modules/
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    ports:
      - "3006:3006"
    depends_on:
      - db
  webpacker:
    image: ${DOCKER_IMAGE_NAME-app}
    env_file:
      - '.env.dev'
    command: ./bin/webpack-dev-server --inline true
    volumes:
      - .:/app:cached
      # use cached bundle and node modules volume
      - bundle:/bundle 
      # put all the generated files into Docker volumes to avoid heavy disk operations on the host machine
      - node_modules:/app/node_modules/
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    ports:
      - '3036:3036'
    depends_on:
    - web
volumes:
  bundle:
  node_modules:
  packs:
  rails_cache:
